//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MI.AriBilgi.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class hakkinda
    {
        public int HakkindaID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Aciklama { get; set; }
    }
}
