//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MI.AriBilgi.DLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlogSiteDBEntities : DbContext
    {
        public BlogSiteDBEntities()
            : base("name=BlogSiteDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Articles> Articles { get; set; }
        public virtual DbSet<ArticlesPictures> ArticlesPictures { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Etiket> Etiket { get; set; }
        public virtual DbSet<hakkinda> hakkinda { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectPictures> ProjectPictures { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Uyeler> Uyeler { get; set; }
        public virtual DbSet<Yetenek> Yetenek { get; set; }
        public virtual DbSet<Yetkiler> Yetkiler { get; set; }
        public virtual DbSet<Yorum> Yorum { get; set; }
    }
}
