//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MI.AriBilgi.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectPictures
    {
        public int Id { get; set; }
        public byte[] PictureSmall { get; set; }
        public byte[] PictureMedium { get; set; }
        public byte[] PictureLarge { get; set; }
        public string ProjectId { get; set; }
    }
}
