//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MI.AriBilgi.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Beceriler { get; set; }
        public string Sure { get; set; }
        public Nullable<int> Fiyat { get; set; }
        public string Url { get; set; }
        public byte[] Resim { get; set; }
    }
}
